[project]
name = "cric-info"
version = "0.1.0"
description = "A cricket information app."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "feedparser>=6.0.12",
    "streamlit>=1.51.0",
]
